#page title
page_title                                : Bokha - Food Allergy Scanner App  # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1628130548                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/bokha-product-scanner/id1628130548    # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.gsy.scallergy       # Enter Google Play Store URL.
#presskit_download_link                    : https://www.soosee.app/presskitEN                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").
app_icon                                  : ./assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Bokha - Food Scanner
app_price                                 : Free Food Allergy Scanner App             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Check products to find allergens in less than a second.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Alexandre Grisey                                
your_link                                 : https://alexandre-grisey.fr/
your_city                                 :                             
email_address                             : pro@alexandre-grisey.fr
#facebook_username                         : sooseeapp
instagram_username                        : alex_gsy
twitter_username                          : nomalex_
github_username                           : Alex0x47
#youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Product Allergens & Traces App Scanner
    description                           : Bokha scans product barcodes to retrieve allergens & traces among 13 different allergens
    fontawesome_icon_name                 : barcode
    
  - title                                 : Set the Allergens you Want to Detect in Products
    description                           : Tell Bokha wich allergens you want to detect, the app will tell you right away if the product contains them!
    fontawesome_icon_name                 : wheat-awn-circle-exclamation

  - title                                 : Favorite and Sharable Products
    description                           : Youn found a product without allergens? You can put it in favorite, and even share it to other
    fontawesome_icon_name                 : heart

  - title                                 : Work All Around the World
    description                           : Can work all around the world - if the product is present in the database
    fontawesome_icon_name                 : globe

  # - title                                 : Useful around the world
  #   description                           : Soosee scans for allergies in English, Dutch, French, German, Italian, Polish, Portuguese, Spanish, Hungarian, Finnish, Danish, Norwegian, Turkish, Lithuanian and Swedish. With more to come!
  #   fontawesome_icon_name                 : flag


  

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"











####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown